parameters:
    shop_id: 1
    customers: 100000
    manufacturers: 1000
    suppliers: 100
    addresses: 10000
    aliases: 100
    categories: 1
    warehouses: 2
    carriers: 3
    specific_prices: 100
    attribute_groups: 10
    products: 1
    attributes: 1
    carts: 1000
    cart_rules: 100
    customizations: 10
    features: 1
    feature_values: 1
    orders: 10
    guests: 10
    order_histories: 6
    range_prices: 100
    range_weights: 100
    product_attributes: 1
    images: 0
    order_messages: 100
    deliveries: 100
    connections: 1000
    product_suppliers: 1
    order_carriers: 2
    order_details: 10
    feature_products: 1
    stores: 100
    profiles: 10
    stock_availables: 1
    langs:
        - fr_FR
        - en_US
