---
netaffiliation:
   catalogs:
    - https://flux.netaffiliation.com/feed.php?maff=C1D8A9FCP4C99D459832158239105875L44D2FV4
    columns:
    - Nom catégorie 
    - Id catégorie  
    - Id catégorie affilié  
    - Nom catégorie affilié 
    - Catégorie marchand  
    - Délais de livraison 
    - Descriptif  
    - Disponibilité 
    - EAN 
    - Ecotaxe 
    - Frais de ports  
    - Garantie  
    - Id produit  
    - Indicateur de nouveauté 
    - Indicateur de performance 
    - Indicateur de promotion 
    - Indicateur de solde 
    - Indicateur de stock 
    - Marque  
    - Modèle  
    - Monnaie 
    - Nom 
    - Prix TTC  
    - Prix barré  
    - Prix HT 
    - Quantité  
    - Référence constructeur  
    - Référence interne 
    - Url 
    - Url de tracking des affichages  
    - Url image grande  
    - Url image moyenne 
    - Url image petite  
    - Url image marchand  