---
config:
  name: OpenFoodFact Import
  version: 0.1
  source: 
    path: ../../../shared/datasets/en.openfoodfacts.org.products.csv # auto-detect local or remote
    remote:
      protocol: http,https,ftp,sftp
      login: ""
      password: ""
      secret_key: ""
      port: 22
  encode: utf8 # ansi
  delimiter: ',' # CSV Field Delimiter
  headers: true
  rows: all # or 0,1000 Items to import
  processor:
    multilang: false
    items: 
      new: ignore #, add
      exists: update, #, ignore
    product: 
      type: standard, # virtual
      identify:
        existing: "Product Name", # Product ID,Reference code,EAN-13 or JAN barcode,UPC barcode,Supplier reference
        # Identify Existing Combination by Matching Field:
        combination: "Attributes" # Combi Reference code, Combi EAN-13 or JAN barcode, Combi UPC barcode
      quantity: "new_quantity" # increase_quantity
      combination:
        autoremove: false # Remove Combination if Combiantion quantity = 0
      feature:
        create: true # Create Feature as Customize Feature if not exist
    category: 
      create: true # Add New Categories if Categories not exist:
      update_strategy: "more_categories" # Add more Categories, new_categories (Remove all OLD categories & Add New)
      delimiter: '/' # Category's Delimiter
    manufacturer:
      create: true # Add New Manufacturer if Manufacturer not exist
    supplier:
      create: true # Add New Suppliers if Suppliers not exist

mapping:
  address:
  customer:
  order:
  product: